universe   = vanilla

executable = job.sh
arguments  = $(Config)

output     = out/exp.$(ClusterId).$(ProcId).out
error      = err/exp.$(ClusterId).$(ProcId).err
log        = log/exp.$(ClusterId).log

transfer_input_files = ../run_functions.py
transfer_output_files = ""

#request_disk = 25000000

requirements = regexp("(V100|A100)", Target.CUDADeviceName)

request_GPUs = 1

+JobFlavour = "testmatch"

+AccountingGroup = "group_u_BE.ABP.normal"

queue Config from configs/config_list.txt